name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  # to be able to manage labels on the release PRs
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v4
        with:
          release-type: simple
